### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by guido4000** [developit/preact-boilerplate#119]
npm@4.1.2 / node/7.5.0

I cloned the repo and ran npm install. When running 'npm run build' or 'npm run dev' I get the following error:

```
npm run build

> preact-boilerplate@5.0.0 prebuild /Users/main12/Projects/fun/preact/aphorism2
> mkdirp build && ncp src/assets build/assets


> preact-boilerplate@5.0.0 build /Users/main12/Projects/fun/preact/aphorism2
> cross-env NODE_ENV=production webpack -p --progress

module.js:472
    throw err;
    ^

Error: Cannot find module './lib/plugin.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/main12/Projects/fun/preact/aphorism2/node_modules/script-ext-html-webpack-plugin/index.js:3:36)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/main12/Projects/fun/preact/aphorism2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/main12/Projects/fun/preact/aphorism2/webpack.config.babel.js:10:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/main12/Projects/fun/preact/aphorism2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/main12/Projects/fun/preact/aphorism2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! preact-boilerplate@5.0.0 build: `cross-env NODE_ENV=production webpack -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the preact-boilerplate@5.0.0 build script 'cross-env NODE_ENV=production webpack -p --progress'.
```

**Comment by developit** [comment]
hi @guido4000 - does it work if you comment out [these three lines](https://github.com/developit/preact-boilerplate/blob/master/webpack.config.babel.js#L105-L107)?  Thanks!

**Comment by developit** [comment]
@guido4000 ah - looks like you cloned and installed just after `script-ext-webpack-plugin` released an update that broke things!  Greenkeeper just notified us about it [here](https://github.com/developit/preact-boilerplate/pull/118).

**Comment by developit** [comment]
I've just removed it for now until it works again.

**Comment by guido4000** [comment]
Great. Thank you.
