### ISSUE TITLE
npm run build failes

### ISSUE THREAD

**Issue by micksp** [developit/preact-boilerplate#218]
I cloned the boilerplate today and follwed the setup instructions. 
The serve workes on localhost:8080 but when i try to build i get the following error: 

>  sperb003@L0139230-3 ~/work/scola/classmobile $ npm run build
> 
> > classmobile@1.0.0 build /home/sperb003/work/scola/classmobile_preact_self
> > preact build
> 
> ./src/components/app.js
> Module build failed: SyntaxError: Unexpected token (15:13)
> 
>   13 |   *      @param {string} event.url       The newly routed URL
>   14 |   */
> > 15 |  handleRoute = e => {
>      |              ^
>   16 |          this.currentUrl = e.url;
>   17 |  };
>   18 | 
> 
>  @ ./src/index.js 9:11-38
>  @ multi ./src/index.js
> Build failed!
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! classmobile@1.0.0 build: `preact build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the classmobile@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/sperb003/.npm/_logs/2017-08-22T08_16_04_205Z-debug.log
> 

The JS error seems to me to be valid ES6 syntax, so I don't understand the error message. 
The mentioned log file: 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/sperb003/.nvm/versions/node/v8.4.0/bin/node',
> 1 verbose cli   '/home/sperb003/.nvm/versions/node/v8.4.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@5.3.0
> 3 info using node@v8.4.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle classmobile@1.0.0~prebuild: classmobile@1.0.0
> 6 info lifecycle classmobile@1.0.0~build: classmobile@1.0.0
> 7 verbose lifecycle classmobile@1.0.0~build: unsafe-perm in lifecycle true
> 8 verbose lifecycle classmobile@1.0.0~build: PATH: /home/sperb003/.nvm/versions/node/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/home/sperb003/work/scola/classmobile_preact_self/node_modules/.bin:/home/sperb003/.nvm/versions/node/v8.4.0/bin:/home/sperb003/bin:/home/sperb003/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
> 9 verbose lifecycle classmobile@1.0.0~build: CWD: /home/sperb003/work/scola/classmobile_preact_self
> 10 silly lifecycle classmobile@1.0.0~build: Args: [ '-c', 'preact build' ]
> 11 silly lifecycle classmobile@1.0.0~build: Returned: code: 1  signal: null
> 12 info lifecycle classmobile@1.0.0~build: Failed to exec build script
> 13 verbose stack Error: classmobile@1.0.0 build: `preact build`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/home/sperb003/.nvm/versions/node/v8.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
> 13 verbose stack     at emitTwo (events.js:125:13)
> 13 verbose stack     at EventEmitter.emit (events.js:213:7)
> 13 verbose stack     at ChildProcess.<anonymous> (/home/sperb003/.nvm/versions/node/v8.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 13 verbose stack     at emitTwo (events.js:125:13)
> 13 verbose stack     at ChildProcess.emit (events.js:213:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:927:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 14 verbose pkgid classmobile@1.0.0
> 15 verbose cwd /home/sperb003/work/scola/classmobile_preact_self
> 16 verbose Linux 4.10.0-32-generic
> 17 verbose argv "/home/sperb003/.nvm/versions/node/v8.4.0/bin/node" "/home/sperb003/.nvm/versions/node/v8.4.0/bin/npm" "run" "build"
> 18 verbose node v8.4.0
> 19 verbose npm  v5.3.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error classmobile@1.0.0 build: `preact build`
> 22 error Exit status 1
> 23 error Failed at the classmobile@1.0.0 build script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 

I tried switching to npm 4 but that gives the same error.

**Comment by micksp** [comment]
well, that was weird. 
I closed my terminal, opened it, cd-ed to the app directory. build works. Sorry for that, false alarm
