### ISSUE TITLE
Help with config?

### ISSUE THREAD

**Issue by zeligon** [developit/preact-boilerplate#232]
Hi,

Full description:
https://github.com/prateekbh/preact-material-components/issues/288

To move forward, tried the following:
- download verify boilerplate's copy works locally (run dev, test, & build) - all looking good
- install preact-material-components onto boilerplate project (``)
- implement `Select` in `home`
- `npm run dev` to verify component shows as intended - looking good 
- now both `npm build` and `npm test` failing

Hope someone here can point me in the right direction. Let me know if more details needed.

Thanks

**Comment by developit** [comment]
Not sure what would cause this. What is the `npm build` failure you're seeing?

**Comment by zeligon** [comment]
Thanks for looking into this!

Here's the log (breaking changes below):
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle awesomeui@1.0.3~prebuild: awesomeui@1.0.3
6 verbose lifecycle awesomeui@1.0.3~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle awesomeui@1.0.3~prebuild: PATH: /Users/zdeveloper/.nvm/versions/node/v6.9.5/lib/node_modules/npm/bin/node-gyp-bin:/Users/zdeveloper/Projects/awesomeui/node_modules/.bin:/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle awesomeui@1.0.3~prebuild: CWD: /Users/zdeveloper/Projects/awesomeui
9 silly lifecycle awesomeui@1.0.3~prebuild: Args: [ '-c', 'mkdirp build && ncp src/assets build/assets' ]
10 silly lifecycle awesomeui@1.0.3~prebuild: Returned: code: 0  signal: null
11 info lifecycle awesomeui@1.0.3~build: awesomeui@1.0.3
12 verbose lifecycle awesomeui@1.0.3~build: unsafe-perm in lifecycle true
13 verbose lifecycle awesomeui@1.0.3~build: PATH: /Users/zdeveloper/.nvm/versions/node/v6.9.5/lib/node_modules/npm/bin/node-gyp-bin:/Users/zdeveloper/Projects/awesomeui/node_modules/.bin:/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle awesomeui@1.0.3~build: CWD: /Users/zdeveloper/Projects/awesomeui
15 silly lifecycle awesomeui@1.0.3~build: Args: [ '-c',
15 silly lifecycle   'cross-env NODE_ENV=production webpack --config ./webpack.config.babel.js --progress --profile --colors' ]
16 silly lifecycle awesomeui@1.0.3~build: Returned: code: 2  signal: null
17 info lifecycle awesomeui@1.0.3~build: Failed to exec build script
18 verbose stack Error: awesomeui@1.0.3 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.babel.js --progress --profile --colors`
18 verbose stack Exit status 2
18 verbose stack     at EventEmitter.<anonymous> (/Users/zdeveloper/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/Users/zdeveloper/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid awesomeui@1.0.3
20 verbose cwd /Users/zdeveloper/Projects/awesomeui
21 error Darwin 16.7.0
22 error argv "/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin/node" "/Users/zdeveloper/.nvm/versions/node/v6.9.5/bin/npm" "run" "build"
23 error node v6.9.5
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error awesomeui@1.0.3 build: `cross-env NODE_ENV=production webpack --config ./webpack.config.babel.js --progress --profile --colors`
26 error Exit status 2
27 error Failed at the awesomeui@1.0.3 build script 'cross-env NODE_ENV=production webpack --config ./webpack.config.babel.js --progress --profile --colors'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the awesomeui package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     cross-env NODE_ENV=production webpack --config ./webpack.config.babel.js --progress --profile --colors
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs awesomeui
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls awesomeui
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

Select component (works):
```
import {h, Component} from 'preact';
import cx from 'classnames';
import 'preact-material-components/List/style.css';
import 'preact-material-components/Menu/style.css';
import 'preact-material-components/Select/style.css';
import style from './style.less';

export default class InputSelect extends Component {
	render( props ) {
		const wrapperClass = props.wrapperClass || style.search_select_wrapper;
		return (
			<div className={wrapperClass}>
				<label htmlFor={props.elementName}>{props.elementTitle}</label>
				<select
					name={props.elementName}
					onChange={props.onChange}
					selectedIndex={props.selectedIndex}
					disabled={props.isDisabled}
					className={cx( 'mdc-select', style.search_select_element )}
				>
					<option>opt1</option>
					<option>opt2</option>
					<option>opt3</option>
					<option>opt4</option>
				</select>
			</div>
		);
	}
}
```
Select component with breaking changes:
```
import {h, Component} from 'preact';
import cx from 'classnames';
**import Select from 'preact-material-components/Select';
import 'preact-material-components/List/style.css';
import 'preact-material-components/Menu/style.css';
import 'preact-material-components/Select/style.css';
import style from './style.less';

export default class SelectPage extends Component {

	render( props ) {
		const wrapperClass = props.wrapperClass || style.search_select_wrapper;
		return (
			<div className={wrapperClass}>
				<label htmlFor={props.elementName}>{props.elementTitle}</label>
**				<Select
					name={props.elementName}
					onChange={props.onChange}
					selectedIndex={props.selectedIndex}
					disabled={props.isDisabled}
					className={cx( 'mdc-select', style.search_select_element )}
				>
**					<Select.Item>opt1</Select.Item>
**					<Select.Item>opt2</Select.Item>
**					<Select.Item>opt3</Select.Item>
**					<Select.Item>opt4</Select.Item>
**				</Select>
			</div>
		);
	}
}
```

**Comment by developit** [comment]
strange.... @prateekbh?

**Comment by prateekbh** [comment]
any repo where i can reproduce this?
