### ISSUE TITLE
Missing caniuse-db and webpack-core module issue on Windows 10

### ISSUE THREAD

**Issue by ubershmekel** [developit/preact-boilerplate#89]
This is what I'm seeing:

```
C:\Users\yuv\Downloads\tmp\pbp>yarn run dev
yarn run v0.17.10
$ cross-env NODE_ENV=development webpack-dev-server --inline --hot --progress
node_modules\nan
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\require-relative\index.js:30:17)
    at resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:26:26)
    at findAndRemove (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:83:11)
    at C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:126:13
    at Array.map (native)
    at loadPreset (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:118:29)
    at module.exports (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\index.js:95:19)
    at Object.<anonymous> (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-preset-es2015-minimal\index.js:5:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\require-relative\index.js:30:17)
    at resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:26:26)
    at findAndRemove (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:83:11)
    at C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:126:13
    at Array.map (native)
    at loadPreset (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:118:29)
    at module.exports (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\index.js:95:19)
    at Object.<anonymous> (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-preset-es2015-minimal\index.js:5:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module 'webpack-core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.requireRelative.resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\require-relative\index.js:30:17)
    at resolve (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:26:26)
    at findAndRemove (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:83:11)
    at C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:126:13
    at Array.map (native)
    at loadPreset (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\lib\serialize.js:118:29)
    at module.exports (C:\Users\yuv\Downloads\tmp\pbp\node_modules\modify-babel-preset\index.js:95:19)
    at Object.<anonymous> (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-preset-es2015-minimal\index.js:5:18)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\yuv\Downloads\tmp\pbp\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17) code: 'MODULE_NOT_FOUND' } webpack-core
 70% 1/1 build modules http://0.0.0.0:8080/
webpack result is served from /
content is served from ./src
404s will fallback to /index.html
Hash: e4c77e621fd5ebe73204
```

The problem does not go away with `yarn add caniuse-db`, or by using `npm`.

**Comment by kuldeepkeshwar** [comment]
dup of https://github.com/developit/preact-boilerplate/issues/88

**Comment by developit** [comment]
Yup, dupe. We'll discuss the fix there! 😊
